config/routes.rb
Rails.application.routes.draw do
  # get 'companies/index'
  # get 'companies/show'
  root to: 'home#index'
  # get 'types/index'
  # get 'types/show'
  # resources :companies, only: [:index, :show]
  # resources :services, only: [:index, :show]
  # resources :clouds, only: [:index, :show]
  # resources :types, only: [:index, :show]
  
  resources :services, only: %i[index show] do
    collection do
      get "search"
    end
  end

  resources :clouds, only: %i[index show] do
    collection do
      get "search"
    end
  end

  resources :types, only: %i[index show] do
    collection do
      get "search"
    end
  end

  resources :companies, only: %i[index show] do
    collection do
      get "search"
    end
  end

  # get 'clouds/index'
  # get 'clouds/show'
  # get 'services/index'
  # get 'services/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cloud.rb
class Cloud < ApplicationRecord
  has_many :services
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :services, through: :service_users
  validates :name, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :cloud
  belongs_to :type
  has_many :companies, through: :service_users
  validates :name, :description, :price, presence: true
end

app/models/service_user.rb
class ServiceUser < ApplicationRecord
  belongs_to :company
  belongs_to :service
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :services
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController
  def index
    @clouds = Cloud.all
  end

  def show
    @cloud = Cloud.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @clouds = Cloud.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  PER_PAGE= 10

  def index
    @page = params.fetch(:page,0).to_i
    @companies = Company.offset(@page * PER_PAGE).limit(PER_PAGE).order("name")
    @all_companies = Company.all
    @numberOfPages = @all_companies.count/PER_PAGE
  end

  def show
    @company = Company.find(params[:id])

    @serviceUser = ServiceUser.where(company_id: @company)

    @service_ids = @serviceUser.map{
      |p| p.service_id
    }

    @services = Service.where(id: @service_ids)



end

def search
  wildcard_search = "%#{params[:keywords]}%"
  @companies = Company.where("name LIKE ?", wildcard_search)
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.includes(:cloud && :type).all.order("name")
  end

  def show
    @services = Service.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @services = Service.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
  end

  def show
    @type = Type.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @types = Type.where("name LIKE ?", wildcard_search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clouds_helper.rb
module CloudsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/clouds/index.html.erb
<h1 class="display-6 mb-4 mt-5 mx-3" > All Cloud Providers </h1>

 <%=  form_with(url: search_clouds_path, method: "get", local:true) do |form|  %>
        <div class="d-flex">
        <%=  text_field_tag(:keywords, nil, class: "form-control me-2", placeholder: "Search for Cloud Providers") %>
        <%= submit_tag("Search", class: "btn btn-outline-success") %>

        </div>
      <% end %>

<ol class="list-group list-group-flush mt-5">
    <% @clouds.each do |cloud| %>
    <li class="list-group-item"> <%= link_to cloud.name, cloud %> </li>
    <% end %>
</ol>

app/views/clouds/search.html.erb
<h1 class="display-6 mb-3 mt-5 mx-3" >
      <%= pluralize(@clouds.count, 'Clouds') %> are found when searching for : <%= params[:keywords] %>
 </h1>

<ol class="list-group list-group-flush" >
<% @clouds.each do |cloud| %>

<li class="list-group-item" > <%= link_to cloud.name, cloud  %> </li>

<% end %>
</ol>

app/views/clouds/show.html.erb
<% content_for(:html_title) {@cloud.name} %>

<h2 class="display-6 mb-3 mt-5 mx-3" > <%= @cloud.name %> </h2>


<samp>Services Proved by <%= @cloud.name %> :</samp>

<ol class="list-group list-group-flush">
    <% @cloud.services.each do |services| %>
    <li class="list-group-item"> <%= link_to services.name, services %> </li>
    <% end %>
</ol>

app/views/companies/index.html.erb
<h1 class="display-6 mb-4 mt-5 mx-3" > All Companies </h1>

<%=  form_with(url: search_companies_path, method: "get", local:true) do |form|  %>
        <div class="d-flex">
        <%=  text_field_tag(:keywords, nil, class: "form-control me-2", placeholder: "Search for Companies") %>
        <%= submit_tag("Search", class: "btn btn-outline-success") %>

        </div>
      <% end %>

<ol class="list-group list-group-flush mt-5" >
<% @companies.each do |company| %>

<li class="list-group-item" > <%= link_to company.name, company  %> </li>

<% end %>
</ol>

<nav aria-label="Page navigation example">
  <ul class="pagination">
  <% for i in 0..@numberOfPages-1 do%>
<li class="page-item"> <div class="page-link" href="#"> <%= link_to i, companies_path(page: i)  %> </div> </li>

  <%end %>

  </ul>
</nav>

app/views/companies/search.html.erb
<h1 class="display-6 mb-3 mt-5 mx-3" >
      <%= pluralize(@companies.count, 'Company') %> are found when searching for : <%= params[:keywords] %>
 </h1>

<ol class="list-group list-group-flush" >
<% @companies.each do |company| %>

<li class="list-group-item" > <%= link_to company.name, company %> </li>

<% end %>
</ol>

app/views/companies/show.html.erb
<% content_for(:html_title) {@company.name} %>

<h2 class="display-6 mb-3 mt-5 mx-3" > <%= @company.name %> </h2>


<h3 class="display-6 mb-3 mt-5 mx-3" > Name of Services Used by <%= @company.name %> Company </h3>

<ol class="list-group list-group-flush" >
<% @services.each do|service|%>
<li class="list-group-item" > <%= link_to service.name, service %> </li>
<% end %>
</ol>

app/views/home/index.html.erb
 <div class="d-flex justify-content-center">
<p class="h4 ">Cloud Project <small class="text-muted">Made by Sahil Mehar</small></p>
</div>

  <div class="mt-5 p-5 container-lg ml-auto  mr-auto  border " >

<%= image_tag "erd.jpg" , width: "840" , height: "540", data: { title: 'ERD Daigram' } %>

 <p class= ' mt-5 '>There are 5 tables in which cloud should have many services but one serice should have one cloud</p>

  <p class= 'mt-5'> One service is of one type whereas types have many services  </p>

   <p class= 'mt-5'> Many companies are using multipe services and many services are used my many companies  </p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title)  + "-" if content_for?(:html_title) %>  Cloud Project  </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="#">Cloud Project</a>
      <ul class="navbar-nav me-auto mb-2  mb-lg-0">
        <li class="nav-item mx-5">
          <a class="nav-link active" aria-current="page" href="/">About</a>
        </li>

         <li class="nav-item mx-5">
          <a class="nav-link active" aria-current="page" href="/clouds">Cloud Servers</a>
        </li>

         <li class="nav-item mx-5">
          <a class="nav-link active" aria-current="page" href="/services"> Services </a>
        </li>


         <li class="nav-item mx-5">
          <a class="nav-link active" aria-current="page" href="/types">Categories</a>
        </li>

         <li class="nav-item mx-5">
          <a class="nav-link active" aria-current="page" href="/companies"> Companies </a>
        </li>

      </ul>
        <%# Here the search form will be imported %>
      
    </div>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/services/index.html.erb
<h1 class="display-6 mb-4 mt-5 mx-3" > All Services </h1>

   <%=  form_with(url: search_services_path, method: "get", local:true) do |form|  %>
        <div class="d-flex">
        <%=  text_field_tag(:keywords, nil, class: "form-control me-2", placeholder: "Search for Services") %>
        <%= submit_tag("Search", class: "btn btn-outline-success") %>

        </div>
      <% end %>

<ol class="list-group list-group-flush mt-5">
    <% @services.each do |service| %>
    <li class="list-group-item mb-2"> <%= link_to service.name, service %> is provided by <%= link_to service.cloud.name, service.cloud  %> Cloud <br>
     and the this is of <%= link_to service.type.name, service.type %>  type
     </li>
    <% end %>
</ol>

app/views/services/search.html.erb
<h1 class="display-6 mb-3 mt-5 mx-3" >
      <%= pluralize(@services.count, 'Services') %> are found when searching for : <%= params[:keywords] %>
 </h1>

<ol class="list-group list-group-flush" >
<% @services.each do |service| %>

<li class="list-group-item" > <%= link_to service.name, service  %> </li>

<% end %>
</ol>

app/views/services/show.html.erb
<% content_for(:html_title) {@services.name} %>

<h2 class="display-5 mb-5 mt-2 " > <%= @services.name %> </h2>

<dl class="row ">
  <dt class="col-sm-3">Service Name</dt>
  <dd class="col-sm-9"> <%= @services.name %> </dd>

  <dt class="col-sm-3">Cloud</dt>
  <dd class="col-sm-9">
    <%= @services.cloud.name %>
  </dd>

  <dt class="col-sm-3">Category</dt>
  <dd class="col-sm-9"><%= @services.type.name %></dd>

  <dt class="col-sm-3 ">Description</dt>
  <dd class="col-sm-9"><%= @services.description %></dd>

  <dt class="col-sm-3 ">Price</dt>
  <dd class="col-sm-9"><%= number_to_currency @services.price %></dd>

</dl>

app/views/types/index.html.erb
<h1 class="display-6 mb-4 mt-5 mx-3" > Service Categories </h1>

 <%=  form_with(url: search_types_path, method: "get", local:true) do |form|  %>
        <div class="d-flex">
        <%=  text_field_tag(:keywords, nil, class: "form-control me-2", placeholder: "Search for Categories") %>
        <%= submit_tag("Search", class: "btn btn-outline-success") %>

        </div>
      <% end %>

<ol class="list-group list-group-flush mt-5">
    <% @types.each do |type| %>
    <li class="list-group-item"> <%= link_to type.name, type %> </li>
    <% end %>
</ol>

app/views/types/search.html.erb
<h1 class="display-6 mb-3 mt-5 mx-3" >
      <%= pluralize(@types.count, 'Categories') %> are found when searching for : <%= params[:keywords] %>
 </h1>

<ol class="list-group list-group-flush" >
<% @types.each do |type| %>

<li class="list-group-item" > <%= link_to type.name, type  %> </li>

<% end %>
</ol>

app/views/types/show.html.erb
<% content_for(:html_title) {@type.name} %>

<h2 class="display-6 mb-3 mt-5 mx-3" > <%= @type.name %> </h2>

<samp>There are following services under <%= @type.name %> Category :</samp>

<ol class="list-group list-group-flush">
    <% @type.services.each do |services| %>
    <li class="list-group-item"> <%= link_to services.name, services %> </li>
    <% end %>
</ol>